### ISSUE TITLE
Invoer tekst niet duidelijk

### ISSUE THREAD

**Issue by wesaidso** [YoYoYasper/Java4Kids#1]
De invoer tekst bij de rekenen class vind ik niet duidelijk. Gaarne aanpassen

**Comment by YoYoYasper** [comment]
je hebt lekker pech
mijn antwoord:
nein
njet 
no
არ
ne
没有

**Comment by wesaidso** [comment]
Veel commentaar vanuit de gebruikers, gaarne aanpassen

**Comment by YoYoYasper** [comment]
ho is op met je gaarne jij garnaal
